name: CI

on:
  release:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Libraries
        id: install_libraries
        run: ./installLibs.sh

      - name: Create Distribution
        id: create_distribution
        run: ./build.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Auto-Camera.zip
          path: Auto-Camera.zip

      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Auto-Camera.zip
          asset_name: Auto-Camera.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Auto-Camera.zip
          asset_name: Auto-Camera-classic.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Auto-Camera.zip
          asset_name: Auto-Camera-bc.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
