name: CI

on:
  release:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Libraries
        id: install_libraries
        run: ./installLibs.sh

      - name: Create Distribution
        id: create_distribution
        run: ./build.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Auto-Camera.zip
          path: Auto-Camera.zip

      - name: Get version from tag
        id: get-version
        uses: actions/github-script@v4
        with:
          script: |
            const version = github.ref.split("/")[2]
            core.setOutput("version", version)

      - name: Upload artifact to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get-version.outputs.version }}
          path: Auto-Camera.zip
