name: CI

on:
  push:
    tags:
      - "[0-9]+\.[0-9]+\.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Libraries
        id: install_libraries
        run: ./installLibs.sh

      - name: Audit TOC files
        id: audit_tocs
        run: bash ./auditTocs.sh

      - name: Create Distribution
        id: create_distribution
        run: ./build.sh "${{ github.ref_name }}"

      - name: Create GitHub release and upload assets
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          files: |
            ./release.json
            ./Auto-Camera-${{ github.ref_name }}*.zip
